### ISSUE TITLE
ng-hcaptcha Error: Uncaught (in promise)

### ISSUE THREAD

**Issue by dedol1** [leNicDev/ng-hcaptcha#63]
I get the below error when I add : <ng-hcaptcha (verify)="onVerify($event)" (expired)="onExpired($event)"
                                                (error)="onError($event)">
                                            </ng-hcaptcha> to my component.html file.

main.ts:6 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'firstCreatePass')
TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:21207:15)
    at definition.providersResolver (core.mjs:21462:24)
    at initializeDirectives (core.mjs:10912:17)
    at resolveDirectives (core.mjs:10886:13)
    at elementStartFirstCreatePass (core.mjs:13558:5)
    at Module.ɵɵelementStart (core.mjs:13594:9)
    at SignupPageComponent_Template (signup-page.component.html:107:45)
    at executeTemplate (core.mjs:10457:9)
    at renderView (core.mjs:10279:13)
    at renderComponent (core.mjs:11450:5)
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1281:17
    at _ZoneDelegate.invokeTask (zone.js:409:31)
    at core.mjs:23891:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23891:36)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Object.onInvokeTask (core.mjs:24192:33)
    at _ZoneDelegate.invokeTask (zone.js:408:60)
    at Zone.runTask (zone.js:178:47)

**Comment by PetarBase** [comment]
I am facing the same issue, using Angular 15 and ng-hcaptcha 2.2.0. Did we find any solution ?

**Comment by dedol1** [comment]
I still haven't been able to identify what the issue is, kindly post your findings here in case you do come across any. I will also do same

**Comment by ArthurIbias** [comment]
same problem...

**Comment by alexsukhodolsky** [comment]
Same problem here. I had to downgrade to version 1.+

**Comment by leNicDev** [comment]
@dedol1 @NicoBrg-WDG @PetarBase @ArthurIbias @alexsukhodolsky Thank you for reporting this issue! I haven't been able to find the root cause yet but I'm going to take some time for it tomorrow 👍

**Comment by mkumar92** [comment]
@leNicDev  have you find any solution for this ?

Thanks

**Comment by mkumar92** [comment]
downgrade the ng hcaptcha 2.2.0 to 2.1.0, solution works for me.

**Comment by Netskeh** [comment]
dropping some info here: I feel like it is related to the version of node you are using to compile. Unfortunately I do not have much time to run additional tests.
I got 2.1.0 not working with node 16.14, but with 16.20
Then 2.2.0 failing with both previous versions, but I expect (NOT TESTED) it to be working with a recent 18.x version?

**Comment by johamguilarte** [comment]
no, with the version of node 16.15.0 it failed, but I changed to the version of node that you mention 18.10, 18.15 and the error persists....

**Comment by jbellionjourdan** [comment]
Hi there,

i had this issue with the following configuration :
angular 15.2.9 
ng-hcaptcha 2.2.0 
Node 18.17.1
npm 9.6.7

Downgrading ng-hcaptcha to 2.1.0 fixed the issue for me. I guess 2.2.0 is just simple incompatible with angular 15 ?
If so, it would be nice to state it in the README :)

**Comment by eb-ib** [comment]
For Angular 14.x, ng-hcaptcha 2.0.0 is the last one that worked in my case.

**Comment by niteshkumar31593-sudo** [comment]
``[](url) gmail hacking
